//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMarcaje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marcaje
    {
        public int id { get; set; }
        public Nullable<int> empleado { get; set; }
        public Nullable<System.DateTime> dia_laboral { get; set; }
        public Nullable<System.TimeSpan> hora_entrada { get; set; }
        public Nullable<System.TimeSpan> hora_entrada_almuerzo { get; set; }
        public Nullable<System.TimeSpan> hora_salida_almuerzo { get; set; }
        public Nullable<System.TimeSpan> hora_salida { get; set; }
    
        public virtual Empleado Empleado1 { get; set; }
    }
}
